AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.1

Metrics:
  Enabled: false

# TODO

Style/Documentation:
  Exclude:
    - 'lib/credit_card_sanitizer.rb'

# Configured

# Layout

Layout/AlignHash:
  EnforcedLastArgumentHashStyle: ignore_implicit
Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
Layout/CaseIndentation:
  EnforcedStyle: end
Layout/FirstParameterIndentation:
  EnforcedStyle: consistent
Layout/IndentArray:
  EnforcedStyle: consistent
Layout/IndentHash:
  EnforcedStyle: consistent
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

# Allow ▇  in comments
Style/AsciiComments:
  Exclude:
    - 'lib/credit_card_sanitizer.rb'

# Lint

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

# Disabled

# Layout

Layout/EmptyLineAfterMagicComment:
  Enabled: false

# Lint

Lint/AssignmentInCondition:
  Enabled: false

# Style

Style/DoubleNegation:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/WordArray:
  Enabled: false
